using System;

[Serializable]
public enum ActionType
{
    JUNKER_HIT, KNIGHT_SLICE, WARCASTER_METALFIST, WARCASTER_MAGIC, HIGHWAYMAN_SHOT, RONIN_SLICE, RONIN_DARKSOUL,
    NINJA_SLICE, NINJA_SHURIKEN, ENGINEER_WRENCH, ENGINEER_REPAIR, MACHINIST_SLASH, MACHINIST_AUTOCROSSBOW,
    NECRONAUT_SPIKE, NECRONAUT_TECHWALL, GUNZERKER_TORCH, GUNZERKER_MINIGUN,
    BATTLEMAIDEN_HIT, VALKYRIE_SLASH, VALKYRIE_BOLT, WITCH_DARKSOUL, WITCH_NIGHTMARE, MEDIC_HEAL,
    RUNEBLADE_SLICE, RUNEBLADE_ALPHASOUL, CORSAIR_DICE, CORSAIR_PISTOL, AMAZON_SHOOT, DRUIDESS_BITE, DRUIDESS_WARD,
    SERAPH_SLAY, SERAPH_JIHAD, MADCAP_FREEZE, MADCAP_REAVE, MORTARMANCER_BOMB
}
