using System;

[Serializable]
public enum CharacterType
{
    JUNKER,KNIGHT,WARCASTER,HIGHWAYMAN,RONIN,NINJA,ENGINEER,MACHINIST,NECRONAUT,GUNZERKER,
    BATTLEMAIDEN,VALKYRIE,WITCH,MEDIC,RUNEBLADE,CORSAIR,AMAZON,DRUIDESS,SERAPH,MADCAP,MORTARMANCER,
}
