using System;

[Serializable]
public enum TargetType
{
    SELF, SELECTED_ENEMY, SELECTED_ALLY, SELECTED_OTHER_ALLY,
    SAME, SAME_IFHIT, SELF_IFHIT,
    ENEMY_LOWEST_HP, ENEMY_HIGHEST_HP, ENEMY_SINGLE_MELEE, ENEMY_SINGLE_RANGED, ENEMY_SINGLE_RANDOM,
    ALLY_LOWEST_HP, ALLY_HIGHEST_HP, ALLY_SINGLE_FALLEN, ALLY_SINGLE_RANDOM,
    ALL_NOT_FALLEN
}
