using System;

[Serializable]
public enum TargetType
{
    SELF, AS_PREVIOUS, AS_PREVIOUS_IF_HIT, SELECTED_ENEMY, SELECTED_ALLY,
    ENEMY_LOWEST_HP, ENEMY_HIGHEST_HP, ENEMY_SINGLE_MELEE, ENEMY_SINGLE_RANGED, ENEMY_SINGLE_RANDOM,
    ALLY_LOWEST_HP, ALLY_HIGHEST_HP, ALLY_SINGLE_FALLEN, ALLY_SINGLE_RANDOM
}
